#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Evangelos A. Dimopoulos"
__copyright__ = "Copyright 2021, University of Oxford"
__email__ = "antonisdim41@gmail.com"
__license__ = "MIT"

import os

from scripts.utilities import REF_GENOME_TABLE, OUT_GENOME_TABLE


include: "rules/snp_calling.smk"
include: "rules/seq_prep.smk"
include: "rules/bt2.smk"
include: "rules/adapterremoval.smk"
include: "rules/htsbox.smk"
include: "rules/fasta_aln.smk"
include: "rules/trees.smk"


rule all:
    input:
        "gatk_mdv/mdv_cluster_ancient_SNP_filter_table.tsv",
        "gatk_mdv/mdv_cluster_ancient_sfs.pdf",
        "aln_mdv/all_seqs_plus_HVT_CM_nstats.tsv",
        "aln_mdv/mdv_modern_plus_HVT_aln.fasta",
        "aln_mdv/mdv_mod_anc_plus_HVT_aln_BEAST.fasta",
        "aln_mdv/mdv_mod_anc_plus_HVT_aln_MLE.fasta",
        "aln_mdv/mdv_mod_anc_no_HVT_aln_BEAST.fasta",
        "trees_mdv/RAxML_bestTree.mdv_plus_HVT_BEAST",
        "trees_mdv/RAxML_bestTree.mdv_plus_HVT_MLE",
        "aux_files/mdv_gene_loci_no_overlap.bed",
        "aux_files/mdv_coding_region.txt",
