#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Evangelos A. Dimopoulos"
__copyright__ = "Copyright 2021, University of Oxford"
__email__ = "antonisdim41@gmail.com"
__license__ = "MIT"

import os

from scripts.utilities import REF_GENOME_TABLE, OUT_GENOME_TABLE


include: "rules/snp_calling.smk"
include: "rules/seq_prep.smk"
include: "rules/bt2.smk"
include: "rules/adapterremoval.smk"


rule all:
    input:
        "gatk_mdv/mdv_cluster_ancient_SNP_filter_table.tsv",
        "gatk_mdv/mdv_cluster_ancient_sfs.pdf",
        expand("modern_genomes/{sample}_ref_{accession}.bam",
            sample=["AF147806.2", "AF243438.1", "AY510475.1", "DQ530348.1", "EF523390.1", "EU499381.1", "FJ436096.1",
                "FJ436097.1", "JF742597.1", "JQ314003.1", "JQ806361.1", "JQ806362.1", "JQ809691.1", "JQ809692.1",
                "JQ820250.1", "JQ836662.1", "JX844666.1", "KT833851.1", "KT833852.1", "KU744555.1", "KU744556.1",
                "KU744557.1", "KU744558.1", "KU744559.1", "KU744560.1", "KU744561.1", "KX290013.1", "KX290014.1",
                "KX290015.1", "KX290016.1", "MG432697.1", "MG518371.1", "NC_002229.3", "NC_002641.1"],
            accession=["EF523390.1"]),
        expand("modern_raw_reads/{sample}_ref_{accession}.bam",
               sample =["KU173115.1", "KU173116.1", "KU173117.1", "KU173118.1", "KU173119.1", "MF431493.1", "MF431494.1",
               "MF431495.1", "MF431496.1"], accession=["EF523390.1"]),
